/**
 * Content Bank — All seeded vocabulary & phrases for SpeakQuest
 *
 * Structure:
 * - ContentItem: a vocabulary word or phrase with all metadata
 * - CONTENT_BANK: flat array of all content items
 * - Helper functions to query/filter content
 *
 * Design for 1 month of daily play:
 * - 8 themes × ~50 words × 3 difficulty levels = ~400 vocab items
 * - 8 themes × ~20 phrases × 3 difficulty levels = ~160 phrases
 * - Total: ~560 content items
 */

export interface ContentItem {
  id: string;
  theme: string; // theme slug
  type: "vocabulary" | "phrase";
  level: "beginner" | "elementary" | "intermediate";
  english: string;
  spanish: string;
  phonetic: string; // approximate pronunciation hint for Spanish speakers
  exampleEn: string; // example sentence in English
  exampleEs: string; // same sentence in Spanish
  hint?: string; // optional hint in Spanish
  tags: string[];
  // For exercise generation:
  distractorsEs?: string[]; // wrong Spanish answers for MC
  distractorsEn?: string[]; // wrong English answers for MC
}

// === Query helpers ===

export function getContentByTheme(theme: string): ContentItem[] {
  return CONTENT_BANK.filter((c) => c.theme === theme);
}

export function getContentByThemeAndLevel(
  theme: string,
  level: string
): ContentItem[] {
  return CONTENT_BANK.filter((c) => c.theme === theme && c.level === level);
}

export function getContentByThemeAndType(
  theme: string,
  type: "vocabulary" | "phrase"
): ContentItem[] {
  return CONTENT_BANK.filter((c) => c.theme === theme && c.type === type);
}

export function getRandomContent(
  theme: string,
  level: string,
  count: number,
  excludeIds: string[] = []
): ContentItem[] {
  const pool = CONTENT_BANK.filter(
    (c) =>
      c.theme === theme &&
      c.level === level &&
      !excludeIds.includes(c.id)
  );
  // Also include items one level easier to create a mix
  const levelOrder = ["beginner", "elementary", "intermediate"];
  const levelIdx = levelOrder.indexOf(level);
  if (levelIdx > 0) {
    const easierLevel = levelOrder[levelIdx - 1];
    const easier = CONTENT_BANK.filter(
      (c) =>
        c.theme === theme &&
        c.level === easierLevel &&
        !excludeIds.includes(c.id)
    );
    // Mix: 70% current level, 30% easier
    const fromCurrent = Math.ceil(count * 0.7);
    const fromEasier = count - fromCurrent;
    return [
      ...shuffleArray(pool).slice(0, fromCurrent),
      ...shuffleArray(easier).slice(0, fromEasier),
    ].slice(0, count);
  }
  return shuffleArray(pool).slice(0, count);
}

export function getContentStats() {
  const stats: Record<string, { vocabulary: number; phrase: number; total: number }> = {};
  for (const item of CONTENT_BANK) {
    if (!stats[item.theme]) stats[item.theme] = { vocabulary: 0, phrase: 0, total: 0 };
    stats[item.theme][item.type]++;
    stats[item.theme].total++;
  }
  return stats;
}

export function getThemeWordCount(theme: string): number {
  return CONTENT_BANK.filter((c) => c.theme === theme).length;
}

function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// === CONTENT BANK ===
// Seeded with real vocabulary and phrases for 1 month of daily play.
// Each theme has vocabulary across beginner/elementary/intermediate levels.

export const CONTENT_BANK: ContentItem[] = [
  // ============================================================
  // THEME: GAMING (gaming)
  // ============================================================
  // --- Beginner ---
  { id: "gaming-v-001", theme: "gaming", type: "vocabulary", level: "beginner", english: "play", spanish: "jugar", phonetic: "pléi", exampleEn: "I play games every day.", exampleEs: "Juego juegos todos los días.", hint: "Empieza por 'pl'", tags: ["verb", "basic"], distractorsEs: ["correr", "comer", "dormir"], distractorsEn: ["run", "eat", "sleep"] },
  { id: "gaming-v-002", theme: "gaming", type: "vocabulary", level: "beginner", english: "game", spanish: "juego", phonetic: "guéim", exampleEn: "This is a fun game.", exampleEs: "Este es un juego divertido.", hint: "Suena como 'guéim'", tags: ["noun", "basic"], distractorsEs: ["libro", "mesa", "silla"], distractorsEn: ["book", "table", "chair"] },
  { id: "gaming-v-003", theme: "gaming", type: "vocabulary", level: "beginner", english: "win", spanish: "ganar", phonetic: "uin", exampleEn: "I want to win!", exampleEs: "¡Quiero ganar!", hint: "Contrario de 'lose'", tags: ["verb", "basic"], distractorsEs: ["perder", "correr", "saltar"], distractorsEn: ["lose", "run", "jump"] },
  { id: "gaming-v-004", theme: "gaming", type: "vocabulary", level: "beginner", english: "lose", spanish: "perder", phonetic: "lúus", exampleEn: "Don't lose the game.", exampleEs: "No pierdas el juego.", hint: "Contrario de 'win'", tags: ["verb", "basic"], distractorsEs: ["ganar", "jugar", "parar"], distractorsEn: ["win", "play", "stop"] },
  { id: "gaming-v-005", theme: "gaming", type: "vocabulary", level: "beginner", english: "player", spanish: "jugador", phonetic: "pléier", exampleEn: "I am a good player.", exampleEs: "Soy un buen jugador.", tags: ["noun", "basic"], distractorsEs: ["maestro", "doctor", "amigo"], distractorsEn: ["teacher", "doctor", "friend"] },
  { id: "gaming-v-006", theme: "gaming", type: "vocabulary", level: "beginner", english: "score", spanish: "puntuación", phonetic: "escór", exampleEn: "My score is 100 points.", exampleEs: "Mi puntuación es 100 puntos.", tags: ["noun", "basic"], distractorsEs: ["tiempo", "vida", "nivel"], distractorsEn: ["time", "life", "level"] },
  { id: "gaming-v-007", theme: "gaming", type: "vocabulary", level: "beginner", english: "start", spanish: "empezar", phonetic: "estárt", exampleEn: "Press start to play.", exampleEs: "Pulsa empezar para jugar.", tags: ["verb", "basic"], distractorsEs: ["parar", "perder", "saltar"], distractorsEn: ["stop", "lose", "jump"] },
  { id: "gaming-v-008", theme: "gaming", type: "vocabulary", level: "beginner", english: "stop", spanish: "parar", phonetic: "estóp", exampleEn: "Stop the game now.", exampleEs: "Para el juego ahora.", tags: ["verb", "basic"], distractorsEs: ["empezar", "correr", "jugar"], distractorsEn: ["start", "run", "play"] },
  { id: "gaming-v-009", theme: "gaming", type: "vocabulary", level: "beginner", english: "jump", spanish: "saltar", phonetic: "yámp", exampleEn: "Jump over the wall!", exampleEs: "¡Salta sobre el muro!", tags: ["verb", "action"], distractorsEs: ["correr", "caer", "volar"], distractorsEn: ["run", "fall", "fly"] },
  { id: "gaming-v-010", theme: "gaming", type: "vocabulary", level: "beginner", english: "run", spanish: "correr", phonetic: "rán", exampleEn: "Run to the finish!", exampleEs: "¡Corre hasta el final!", tags: ["verb", "action"], distractorsEs: ["andar", "saltar", "parar"], distractorsEn: ["walk", "jump", "stop"] },
  { id: "gaming-v-011", theme: "gaming", type: "vocabulary", level: "beginner", english: "life", spanish: "vida", phonetic: "láif", exampleEn: "You have three lives.", exampleEs: "Tienes tres vidas.", tags: ["noun", "basic"], distractorsEs: ["muerte", "punto", "mapa"], distractorsEn: ["death", "point", "map"] },
  { id: "gaming-v-012", theme: "gaming", type: "vocabulary", level: "beginner", english: "hero", spanish: "héroe", phonetic: "jírou", exampleEn: "The hero saves the world.", exampleEs: "El héroe salva el mundo.", tags: ["noun", "character"], distractorsEs: ["villano", "amigo", "mago"], distractorsEn: ["villain", "friend", "wizard"] },
  // --- Elementary ---
  { id: "gaming-v-013", theme: "gaming", type: "vocabulary", level: "elementary", english: "level", spanish: "nivel", phonetic: "lével", exampleEn: "I reached level 10!", exampleEs: "¡Llegué al nivel 10!", tags: ["noun", "progress"], distractorsEs: ["ronda", "turno", "fase"], distractorsEn: ["round", "turn", "phase"] },
  { id: "gaming-v-014", theme: "gaming", type: "vocabulary", level: "elementary", english: "team", spanish: "equipo", phonetic: "tíim", exampleEn: "Join my team!", exampleEs: "¡Únete a mi equipo!", tags: ["noun", "social"], distractorsEs: ["enemigo", "rival", "grupo"], distractorsEn: ["enemy", "rival", "group"] },
  { id: "gaming-v-015", theme: "gaming", type: "vocabulary", level: "elementary", english: "power", spanish: "poder", phonetic: "páuer", exampleEn: "This power is amazing!", exampleEs: "¡Este poder es increíble!", tags: ["noun", "ability"], distractorsEs: ["debilidad", "fuerza", "magia"], distractorsEn: ["weakness", "strength", "magic"] },
  { id: "gaming-v-016", theme: "gaming", type: "vocabulary", level: "elementary", english: "shield", spanish: "escudo", phonetic: "shíild", exampleEn: "Use the shield to block.", exampleEs: "Usa el escudo para bloquear.", tags: ["noun", "item"], distractorsEs: ["espada", "casco", "armadura"], distractorsEn: ["sword", "helmet", "armor"] },
  { id: "gaming-v-017", theme: "gaming", type: "vocabulary", level: "elementary", english: "sword", spanish: "espada", phonetic: "sórd", exampleEn: "The hero has a magic sword.", exampleEs: "El héroe tiene una espada mágica.", tags: ["noun", "item"], distractorsEs: ["escudo", "arco", "lanza"], distractorsEn: ["shield", "bow", "spear"] },
  { id: "gaming-v-018", theme: "gaming", type: "vocabulary", level: "elementary", english: "quest", spanish: "misión", phonetic: "kuést", exampleEn: "Complete the quest to get a reward.", exampleEs: "Completa la misión para obtener una recompensa.", tags: ["noun", "mission"], distractorsEs: ["batalla", "aventura", "premio"], distractorsEn: ["battle", "adventure", "prize"] },
  { id: "gaming-v-019", theme: "gaming", type: "vocabulary", level: "elementary", english: "enemy", spanish: "enemigo", phonetic: "énimi", exampleEn: "Watch out for the enemy!", exampleEs: "¡Cuidado con el enemigo!", tags: ["noun", "character"], distractorsEs: ["amigo", "héroe", "aliado"], distractorsEn: ["friend", "hero", "ally"] },
  { id: "gaming-v-020", theme: "gaming", type: "vocabulary", level: "elementary", english: "treasure", spanish: "tesoro", phonetic: "tréshur", exampleEn: "Find the hidden treasure.", exampleEs: "Encuentra el tesoro escondido.", tags: ["noun", "item"], distractorsEs: ["trampa", "cueva", "mapa"], distractorsEn: ["trap", "cave", "map"] },
  { id: "gaming-v-021", theme: "gaming", type: "vocabulary", level: "elementary", english: "map", spanish: "mapa", phonetic: "máp", exampleEn: "Open the map to find the way.", exampleEs: "Abre el mapa para encontrar el camino.", tags: ["noun", "item"], distractorsEs: ["libro", "tesoro", "brújula"], distractorsEn: ["book", "treasure", "compass"] },
  { id: "gaming-v-022", theme: "gaming", type: "vocabulary", level: "elementary", english: "battle", spanish: "batalla", phonetic: "bátol", exampleEn: "The final battle is here!", exampleEs: "¡La batalla final está aquí!", tags: ["noun", "action"], distractorsEs: ["fiesta", "carrera", "descanso"], distractorsEn: ["party", "race", "rest"] },
  { id: "gaming-v-023", theme: "gaming", type: "vocabulary", level: "elementary", english: "attack", spanish: "atacar", phonetic: "aták", exampleEn: "Attack the monster!", exampleEs: "¡Ataca al monstruo!", tags: ["verb", "action"], distractorsEs: ["defender", "huir", "esconder"], distractorsEn: ["defend", "flee", "hide"] },
  { id: "gaming-v-024", theme: "gaming", type: "vocabulary", level: "elementary", english: "defend", spanish: "defender", phonetic: "difénd", exampleEn: "Defend the castle from enemies.", exampleEs: "Defiende el castillo de los enemigos.", tags: ["verb", "action"], distractorsEs: ["atacar", "destruir", "rendirse"], distractorsEn: ["attack", "destroy", "surrender"] },
  // --- Intermediate ---
  { id: "gaming-v-025", theme: "gaming", type: "vocabulary", level: "intermediate", english: "achievement", spanish: "logro", phonetic: "achívment", exampleEn: "I unlocked a new achievement!", exampleEs: "¡Desbloqueé un nuevo logro!", tags: ["noun", "progress"], distractorsEs: ["fracaso", "intento", "nivel"], distractorsEn: ["failure", "attempt", "level"] },
  { id: "gaming-v-026", theme: "gaming", type: "vocabulary", level: "intermediate", english: "challenge", spanish: "desafío", phonetic: "chálench", exampleEn: "This challenge is really hard.", exampleEs: "Este desafío es muy difícil.", tags: ["noun", "difficulty"], distractorsEs: ["premio", "tutorial", "pausa"], distractorsEn: ["prize", "tutorial", "pause"] },
  { id: "gaming-v-027", theme: "gaming", type: "vocabulary", level: "intermediate", english: "strategy", spanish: "estrategia", phonetic: "strátedyi", exampleEn: "We need a good strategy.", exampleEs: "Necesitamos una buena estrategia.", tags: ["noun", "planning"], distractorsEs: ["suerte", "trampa", "velocidad"], distractorsEn: ["luck", "cheat", "speed"] },
  { id: "gaming-v-028", theme: "gaming", type: "vocabulary", level: "intermediate", english: "upgrade", spanish: "mejora", phonetic: "apgréid", exampleEn: "Upgrade your weapons to be stronger.", exampleEs: "Mejora tus armas para ser más fuerte.", tags: ["noun", "progress"], distractorsEs: ["venta", "compra", "intercambio"], distractorsEn: ["sale", "purchase", "trade"] },
  { id: "gaming-v-029", theme: "gaming", type: "vocabulary", level: "intermediate", english: "respawn", spanish: "reaparecer", phonetic: "rispón", exampleEn: "You will respawn at the checkpoint.", exampleEs: "Reaparecerás en el punto de control.", tags: ["verb", "mechanics"], distractorsEs: ["morir", "escapar", "guardar"], distractorsEn: ["die", "escape", "save"] },
  { id: "gaming-v-030", theme: "gaming", type: "vocabulary", level: "intermediate", english: "inventory", spanish: "inventario", phonetic: "invéntori", exampleEn: "Check your inventory for potions.", exampleEs: "Revisa tu inventario para buscar pociones.", tags: ["noun", "item"], distractorsEs: ["tienda", "mochila", "almacén"], distractorsEn: ["shop", "backpack", "storage"] },
  // Gaming phrases
  { id: "gaming-p-001", theme: "gaming", type: "phrase", level: "beginner", english: "Let's play!", spanish: "¡Vamos a jugar!", phonetic: "lets pléi", exampleEn: "Let's play a new game together.", exampleEs: "Vamos a jugar un juego nuevo juntos.", tags: ["invitation", "fun"], distractorsEs: ["¡Vamos a comer!", "¡Vamos a dormir!", "¡Vamos a casa!"], distractorsEn: ["Let's eat!", "Let's sleep!", "Let's go home!"] },
  { id: "gaming-p-002", theme: "gaming", type: "phrase", level: "beginner", english: "I won!", spanish: "¡Gané!", phonetic: "ái uón", exampleEn: "I won the game!", exampleEs: "¡Gané el juego!", tags: ["celebration", "result"], distractorsEs: ["¡Perdí!", "¡Empaté!", "¡Me rendí!"], distractorsEn: ["I lost!", "It's a tie!", "I gave up!"] },
  { id: "gaming-p-003", theme: "gaming", type: "phrase", level: "beginner", english: "Game over", spanish: "Fin del juego", phonetic: "guéim óuver", exampleEn: "Oh no, game over!", exampleEs: "¡Oh no, fin del juego!", tags: ["ending", "result"], distractorsEs: ["Nuevo juego", "Pausa", "Continuar"], distractorsEn: ["New game", "Pause", "Continue"] },
  { id: "gaming-p-004", theme: "gaming", type: "phrase", level: "elementary", english: "It's my turn", spanish: "Es mi turno", phonetic: "its mái tern", exampleEn: "Wait, it's my turn now.", exampleEs: "Espera, ahora es mi turno.", tags: ["social", "turns"], distractorsEs: ["Es tu turno", "Es su turno", "No hay turno"], distractorsEn: ["It's your turn", "It's their turn", "No turns"] },
  { id: "gaming-p-005", theme: "gaming", type: "phrase", level: "elementary", english: "Watch out!", spanish: "¡Cuidado!", phonetic: "uóch áut", exampleEn: "Watch out! The enemy is behind you!", exampleEs: "¡Cuidado! ¡El enemigo está detrás de ti!", tags: ["warning", "action"], distractorsEs: ["¡Bien hecho!", "¡Vamos!", "¡Espera!"], distractorsEn: ["Well done!", "Let's go!", "Wait!"] },
  { id: "gaming-p-006", theme: "gaming", type: "phrase", level: "intermediate", english: "That was a close call", spanish: "Eso estuvo cerca", phonetic: "dat uós a clóus col", exampleEn: "Wow, that was a close call! I almost lost.", exampleEs: "¡Guau, eso estuvo cerca! Casi pierdo.", tags: ["expression", "tension"], distractorsEs: ["Fue muy fácil", "No pasó nada", "Es imposible"], distractorsEn: ["It was easy", "Nothing happened", "It's impossible"] },

  // ============================================================
  // THEME: SPORTS (sports)
  // ============================================================
  // --- Beginner ---
  { id: "sports-v-001", theme: "sports", type: "vocabulary", level: "beginner", english: "ball", spanish: "pelota", phonetic: "ból", exampleEn: "Kick the ball!", exampleEs: "¡Patea la pelota!", tags: ["noun", "equipment"], distractorsEs: ["red", "campo", "gol"], distractorsEn: ["net", "field", "goal"] },
  { id: "sports-v-002", theme: "sports", type: "vocabulary", level: "beginner", english: "goal", spanish: "gol", phonetic: "góul", exampleEn: "He scored a goal!", exampleEs: "¡Marcó un gol!", tags: ["noun", "scoring"], distractorsEs: ["falta", "córner", "penal"], distractorsEn: ["foul", "corner", "penalty"] },
  { id: "sports-v-003", theme: "sports", type: "vocabulary", level: "beginner", english: "team", spanish: "equipo", phonetic: "tíim", exampleEn: "Our team is the best!", exampleEs: "¡Nuestro equipo es el mejor!", tags: ["noun", "group"], distractorsEs: ["jugador", "árbitro", "público"], distractorsEn: ["player", "referee", "crowd"] },
  { id: "sports-v-004", theme: "sports", type: "vocabulary", level: "beginner", english: "kick", spanish: "patear", phonetic: "kik", exampleEn: "Kick the ball hard!", exampleEs: "¡Patea la pelota fuerte!", tags: ["verb", "action"], distractorsEs: ["lanzar", "atrapar", "correr"], distractorsEn: ["throw", "catch", "run"] },
  { id: "sports-v-005", theme: "sports", type: "vocabulary", level: "beginner", english: "swim", spanish: "nadar", phonetic: "suím", exampleEn: "I love to swim.", exampleEs: "Me encanta nadar.", tags: ["verb", "action"], distractorsEs: ["correr", "saltar", "caminar"], distractorsEn: ["run", "jump", "walk"] },
  { id: "sports-v-006", theme: "sports", type: "vocabulary", level: "beginner", english: "fast", spanish: "rápido", phonetic: "fast", exampleEn: "She runs very fast.", exampleEs: "Ella corre muy rápido.", tags: ["adjective", "speed"], distractorsEs: ["lento", "alto", "fuerte"], distractorsEn: ["slow", "tall", "strong"] },
  { id: "sports-v-007", theme: "sports", type: "vocabulary", level: "beginner", english: "coach", spanish: "entrenador", phonetic: "cóuch", exampleEn: "The coach helps the team.", exampleEs: "El entrenador ayuda al equipo.", tags: ["noun", "person"], distractorsEs: ["jugador", "árbitro", "capitán"], distractorsEn: ["player", "referee", "captain"] },
  { id: "sports-v-008", theme: "sports", type: "vocabulary", level: "beginner", english: "race", spanish: "carrera", phonetic: "réis", exampleEn: "I won the race!", exampleEs: "¡Gané la carrera!", tags: ["noun", "competition"], distractorsEs: ["partido", "torneo", "liga"], distractorsEn: ["match", "tournament", "league"] },
  { id: "sports-v-009", theme: "sports", type: "vocabulary", level: "beginner", english: "strong", spanish: "fuerte", phonetic: "stróng", exampleEn: "He is very strong.", exampleEs: "Él es muy fuerte.", tags: ["adjective", "quality"], distractorsEs: ["débil", "rápido", "alto"], distractorsEn: ["weak", "fast", "tall"] },
  { id: "sports-v-010", theme: "sports", type: "vocabulary", level: "beginner", english: "throw", spanish: "lanzar", phonetic: "zróu", exampleEn: "Throw the ball to me!", exampleEs: "¡Lánzame la pelota!", tags: ["verb", "action"], distractorsEs: ["atrapar", "patear", "golpear"], distractorsEn: ["catch", "kick", "hit"] },
  // --- Elementary ---
  { id: "sports-v-011", theme: "sports", type: "vocabulary", level: "elementary", english: "referee", spanish: "árbitro", phonetic: "réferi", exampleEn: "The referee gave a red card.", exampleEs: "El árbitro sacó una tarjeta roja.", tags: ["noun", "person"], distractorsEs: ["entrenador", "capitán", "portero"], distractorsEn: ["coach", "captain", "goalkeeper"] },
  { id: "sports-v-012", theme: "sports", type: "vocabulary", level: "elementary", english: "champion", spanish: "campeón", phonetic: "chámpiun", exampleEn: "Our team is the champion!", exampleEs: "¡Nuestro equipo es el campeón!", tags: ["noun", "title"], distractorsEs: ["perdedor", "segundo", "último"], distractorsEn: ["loser", "second", "last"] },
  { id: "sports-v-013", theme: "sports", type: "vocabulary", level: "elementary", english: "stadium", spanish: "estadio", phonetic: "estéidium", exampleEn: "The stadium is full of fans.", exampleEs: "El estadio está lleno de aficionados.", tags: ["noun", "place"], distractorsEs: ["gimnasio", "piscina", "pista"], distractorsEn: ["gym", "pool", "track"] },
  { id: "sports-v-014", theme: "sports", type: "vocabulary", level: "elementary", english: "match", spanish: "partido", phonetic: "mách", exampleEn: "The match starts at 3 o'clock.", exampleEs: "El partido empieza a las 3.", tags: ["noun", "event"], distractorsEs: ["entrenamiento", "descanso", "final"], distractorsEn: ["training", "break", "final"] },
  { id: "sports-v-015", theme: "sports", type: "vocabulary", level: "elementary", english: "trophy", spanish: "trofeo", phonetic: "trófi", exampleEn: "They lifted the trophy!", exampleEs: "¡Levantaron el trofeo!", tags: ["noun", "prize"], distractorsEs: ["medalla", "copa", "bandera"], distractorsEn: ["medal", "cup", "flag"] },
  { id: "sports-v-016", theme: "sports", type: "vocabulary", level: "elementary", english: "practice", spanish: "practicar", phonetic: "práctis", exampleEn: "I practice every afternoon.", exampleEs: "Practico todas las tardes.", tags: ["verb", "training"], distractorsEs: ["descansar", "competir", "ganar"], distractorsEn: ["rest", "compete", "win"] },
  { id: "sports-v-017", theme: "sports", type: "vocabulary", level: "elementary", english: "score", spanish: "marcador", phonetic: "escór", exampleEn: "The score is 2-1.", exampleEs: "El marcador es 2-1.", tags: ["noun", "result"], distractorsEs: ["tiempo", "campo", "portería"], distractorsEn: ["time", "field", "goal post"] },
  { id: "sports-v-018", theme: "sports", type: "vocabulary", level: "elementary", english: "catch", spanish: "atrapar", phonetic: "cách", exampleEn: "Catch the ball!", exampleEs: "¡Atrapa la pelota!", tags: ["verb", "action"], distractorsEs: ["lanzar", "patear", "pasar"], distractorsEn: ["throw", "kick", "pass"] },
  // --- Intermediate ---
  { id: "sports-v-019", theme: "sports", type: "vocabulary", level: "intermediate", english: "tournament", spanish: "torneo", phonetic: "tórnament", exampleEn: "The tournament has 16 teams.", exampleEs: "El torneo tiene 16 equipos.", tags: ["noun", "competition"], distractorsEs: ["liga", "copa", "partido"], distractorsEn: ["league", "cup", "match"] },
  { id: "sports-v-020", theme: "sports", type: "vocabulary", level: "intermediate", english: "defeat", spanish: "derrotar", phonetic: "difít", exampleEn: "We defeated the other team 3-0.", exampleEs: "Derrotamos al otro equipo 3-0.", tags: ["verb", "result"], distractorsEs: ["empatar", "perder", "rendirse"], distractorsEn: ["tie", "lose", "surrender"] },
  { id: "sports-v-021", theme: "sports", type: "vocabulary", level: "intermediate", english: "goalkeeper", spanish: "portero", phonetic: "góulkíper", exampleEn: "The goalkeeper saved the penalty!", exampleEs: "¡El portero paró el penal!", tags: ["noun", "position"], distractorsEs: ["delantero", "defensa", "mediocampista"], distractorsEn: ["forward", "defender", "midfielder"] },
  { id: "sports-v-022", theme: "sports", type: "vocabulary", level: "intermediate", english: "fitness", spanish: "forma física", phonetic: "fítnes", exampleEn: "Good fitness is important for athletes.", exampleEs: "La buena forma física es importante para los atletas.", tags: ["noun", "health"], distractorsEs: ["cansancio", "lesión", "dieta"], distractorsEn: ["tiredness", "injury", "diet"] },
  // Sports phrases
  { id: "sports-p-001", theme: "sports", type: "phrase", level: "beginner", english: "Pass the ball!", spanish: "¡Pasa la pelota!", phonetic: "pas de ból", exampleEn: "Quick, pass the ball to me!", exampleEs: "¡Rápido, pásame la pelota!", tags: ["command", "teamwork"], distractorsEs: ["¡Tira la pelota!", "¡Para la pelota!", "¡Roba la pelota!"], distractorsEn: ["Shoot the ball!", "Stop the ball!", "Steal the ball!"] },
  { id: "sports-p-002", theme: "sports", type: "phrase", level: "beginner", english: "Good game!", spanish: "¡Buen partido!", phonetic: "gud guéim", exampleEn: "Good game, everyone!", exampleEs: "¡Buen partido, todos!", tags: ["sportsmanship"], distractorsEs: ["¡Mal partido!", "¡Qué aburrido!", "¡Qué injusto!"], distractorsEn: ["Bad game!", "How boring!", "How unfair!"] },
  { id: "sports-p-003", theme: "sports", type: "phrase", level: "elementary", english: "What's the score?", spanish: "¿Cuál es el marcador?", phonetic: "uóts de escór", exampleEn: "What's the score right now?", exampleEs: "¿Cuál es el marcador ahora?", tags: ["question", "game"], distractorsEs: ["¿Quién juega?", "¿Cuándo empieza?", "¿Dónde es?"], distractorsEn: ["Who's playing?", "When does it start?", "Where is it?"] },
  { id: "sports-p-004", theme: "sports", type: "phrase", level: "intermediate", english: "He was offside", spanish: "Estaba en fuera de juego", phonetic: "ji uós ófsáid", exampleEn: "That goal doesn't count, he was offside.", exampleEs: "Ese gol no vale, estaba en fuera de juego.", tags: ["rules", "football"], distractorsEs: ["Fue falta", "Era penal", "Es córner"], distractorsEn: ["It was a foul", "It was a penalty", "It's a corner"] },

  // ============================================================
  // THEME: MOVIES & TV (movies)
  // ============================================================
  { id: "movies-v-001", theme: "movies", type: "vocabulary", level: "beginner", english: "movie", spanish: "película", phonetic: "múuvi", exampleEn: "Let's watch a movie!", exampleEs: "¡Vamos a ver una película!", tags: ["noun", "basic"], distractorsEs: ["canción", "libro", "foto"], distractorsEn: ["song", "book", "photo"] },
  { id: "movies-v-002", theme: "movies", type: "vocabulary", level: "beginner", english: "watch", spanish: "ver", phonetic: "uóch", exampleEn: "I watch TV every day.", exampleEs: "Veo la tele todos los días.", tags: ["verb", "basic"], distractorsEs: ["escuchar", "leer", "jugar"], distractorsEn: ["listen", "read", "play"] },
  { id: "movies-v-003", theme: "movies", type: "vocabulary", level: "beginner", english: "funny", spanish: "divertido", phonetic: "fáni", exampleEn: "This movie is really funny.", exampleEs: "Esta película es muy divertida.", tags: ["adjective", "emotion"], distractorsEs: ["aburrido", "triste", "aterrador"], distractorsEn: ["boring", "sad", "scary"] },
  { id: "movies-v-004", theme: "movies", type: "vocabulary", level: "beginner", english: "scary", spanish: "aterrador", phonetic: "esquéri", exampleEn: "I don't like scary movies.", exampleEs: "No me gustan las películas de terror.", tags: ["adjective", "emotion"], distractorsEs: ["divertido", "triste", "bonito"], distractorsEn: ["funny", "sad", "beautiful"] },
  { id: "movies-v-005", theme: "movies", type: "vocabulary", level: "beginner", english: "story", spanish: "historia", phonetic: "estóri", exampleEn: "This is a great story.", exampleEs: "Esta es una gran historia.", tags: ["noun", "narrative"], distractorsEs: ["canción", "dibujo", "juego"], distractorsEn: ["song", "drawing", "game"] },
  { id: "movies-v-006", theme: "movies", type: "vocabulary", level: "beginner", english: "actor", spanish: "actor", phonetic: "áctor", exampleEn: "He is a famous actor.", exampleEs: "Él es un actor famoso.", tags: ["noun", "person"], distractorsEs: ["director", "cantante", "escritor"], distractorsEn: ["director", "singer", "writer"] },
  { id: "movies-v-007", theme: "movies", type: "vocabulary", level: "beginner", english: "show", spanish: "programa", phonetic: "shóu", exampleEn: "My favorite show is on TV.", exampleEs: "Mi programa favorito está en la tele.", tags: ["noun", "basic"], distractorsEs: ["película", "anuncio", "noticia"], distractorsEn: ["movie", "ad", "news"] },
  { id: "movies-v-008", theme: "movies", type: "vocabulary", level: "beginner", english: "sing", spanish: "cantar", phonetic: "sing", exampleEn: "The characters sing in the movie.", exampleEs: "Los personajes cantan en la película.", tags: ["verb", "action"], distractorsEs: ["bailar", "llorar", "gritar"], distractorsEn: ["dance", "cry", "shout"] },
  { id: "movies-v-009", theme: "movies", type: "vocabulary", level: "elementary", english: "cartoon", spanish: "dibujos animados", phonetic: "cartún", exampleEn: "I like watching cartoons.", exampleEs: "Me gusta ver dibujos animados.", tags: ["noun", "genre"], distractorsEs: ["noticias", "documental", "serie"], distractorsEn: ["news", "documentary", "series"] },
  { id: "movies-v-010", theme: "movies", type: "vocabulary", level: "elementary", english: "character", spanish: "personaje", phonetic: "kérácter", exampleEn: "My favorite character is brave.", exampleEs: "Mi personaje favorito es valiente.", tags: ["noun", "narrative"], distractorsEs: ["actor", "director", "guionista"], distractorsEn: ["actor", "director", "screenwriter"] },
  { id: "movies-v-011", theme: "movies", type: "vocabulary", level: "elementary", english: "adventure", spanish: "aventura", phonetic: "advénchur", exampleEn: "I love adventure movies.", exampleEs: "Me encantan las películas de aventura.", tags: ["noun", "genre"], distractorsEs: ["comedia", "terror", "drama"], distractorsEn: ["comedy", "horror", "drama"] },
  { id: "movies-v-012", theme: "movies", type: "vocabulary", level: "elementary", english: "scene", spanish: "escena", phonetic: "siin", exampleEn: "That was the best scene!", exampleEs: "¡Esa fue la mejor escena!", tags: ["noun", "part"], distractorsEs: ["final", "inicio", "título"], distractorsEn: ["ending", "beginning", "title"] },
  { id: "movies-v-013", theme: "movies", type: "vocabulary", level: "elementary", english: "subtitle", spanish: "subtítulo", phonetic: "sábtaitol", exampleEn: "Turn on the subtitles.", exampleEs: "Pon los subtítulos.", tags: ["noun", "feature"], distractorsEs: ["volumen", "brillo", "pausa"], distractorsEn: ["volume", "brightness", "pause"] },
  { id: "movies-v-014", theme: "movies", type: "vocabulary", level: "intermediate", english: "plot", spanish: "trama", phonetic: "plót", exampleEn: "The plot of this movie is amazing.", exampleEs: "La trama de esta película es increíble.", tags: ["noun", "narrative"], distractorsEs: ["final", "escena", "banda sonora"], distractorsEn: ["ending", "scene", "soundtrack"] },
  { id: "movies-v-015", theme: "movies", type: "vocabulary", level: "intermediate", english: "sequel", spanish: "secuela", phonetic: "síkuel", exampleEn: "The sequel is even better.", exampleEs: "La secuela es aún mejor.", tags: ["noun", "film"], distractorsEs: ["precuela", "remake", "original"], distractorsEn: ["prequel", "remake", "original"] },
  { id: "movies-v-016", theme: "movies", type: "vocabulary", level: "intermediate", english: "soundtrack", spanish: "banda sonora", phonetic: "sáundtrak", exampleEn: "The soundtrack has great songs.", exampleEs: "La banda sonora tiene grandes canciones.", tags: ["noun", "music"], distractorsEs: ["diálogo", "efectos", "guion"], distractorsEn: ["dialogue", "effects", "script"] },
  // Movies phrases
  { id: "movies-p-001", theme: "movies", type: "phrase", level: "beginner", english: "What are you watching?", spanish: "¿Qué estás viendo?", phonetic: "uót ar yú uóching", exampleEn: "Hey, what are you watching?", exampleEs: "Oye, ¿qué estás viendo?", tags: ["question", "social"], distractorsEs: ["¿Qué estás comiendo?", "¿Qué estás leyendo?", "¿Qué estás haciendo?"], distractorsEn: ["What are you eating?", "What are you reading?", "What are you doing?"] },
  { id: "movies-p-002", theme: "movies", type: "phrase", level: "beginner", english: "I love this movie!", spanish: "¡Me encanta esta película!", phonetic: "ái lav dis múuvi", exampleEn: "I love this movie so much!", exampleEs: "¡Me encanta muchísimo esta película!", tags: ["opinion", "positive"], distractorsEs: ["Odio esta película", "No entiendo nada", "Es aburrida"], distractorsEn: ["I hate this movie", "I don't understand", "It's boring"] },
  { id: "movies-p-003", theme: "movies", type: "phrase", level: "elementary", english: "No spoilers, please!", spanish: "¡Sin spoilers, por favor!", phonetic: "nóu espóilers plíis", exampleEn: "Don't tell me! No spoilers, please!", exampleEs: "¡No me lo cuentes! ¡Sin spoilers, por favor!", tags: ["request", "social"], distractorsEs: ["Cuéntame todo", "Dime el final", "No me importa"], distractorsEn: ["Tell me everything", "Tell me the ending", "I don't care"] },
  { id: "movies-p-004", theme: "movies", type: "phrase", level: "intermediate", english: "It's based on a true story", spanish: "Está basada en una historia real", phonetic: "its béist on a trú estóri", exampleEn: "This movie is based on a true story.", exampleEs: "Esta película está basada en una historia real.", tags: ["information", "film"], distractorsEs: ["Es totalmente inventada", "Es un documental", "Es una serie"], distractorsEn: ["It's totally made up", "It's a documentary", "It's a series"] },

  // ============================================================
  // THEME: MUSIC (music)
  // ============================================================
  { id: "music-v-001", theme: "music", type: "vocabulary", level: "beginner", english: "song", spanish: "canción", phonetic: "song", exampleEn: "This is my favorite song.", exampleEs: "Esta es mi canción favorita.", tags: ["noun", "basic"], distractorsEs: ["película", "libro", "juego"], distractorsEn: ["movie", "book", "game"] },
  { id: "music-v-002", theme: "music", type: "vocabulary", level: "beginner", english: "dance", spanish: "bailar", phonetic: "dans", exampleEn: "I like to dance.", exampleEs: "Me gusta bailar.", tags: ["verb", "action"], distractorsEs: ["cantar", "correr", "dormir"], distractorsEn: ["sing", "run", "sleep"] },
  { id: "music-v-003", theme: "music", type: "vocabulary", level: "beginner", english: "music", spanish: "música", phonetic: "miúsic", exampleEn: "I listen to music.", exampleEs: "Escucho música.", tags: ["noun", "basic"], distractorsEs: ["ruido", "silencio", "voz"], distractorsEn: ["noise", "silence", "voice"] },
  { id: "music-v-004", theme: "music", type: "vocabulary", level: "beginner", english: "loud", spanish: "alto/fuerte", phonetic: "láud", exampleEn: "The music is too loud!", exampleEs: "¡La música está muy alta!", tags: ["adjective", "volume"], distractorsEs: ["bajo", "rápido", "lento"], distractorsEn: ["quiet", "fast", "slow"] },
  { id: "music-v-005", theme: "music", type: "vocabulary", level: "beginner", english: "listen", spanish: "escuchar", phonetic: "lísen", exampleEn: "Listen to this song!", exampleEs: "¡Escucha esta canción!", tags: ["verb", "basic"], distractorsEs: ["mirar", "hablar", "tocar"], distractorsEn: ["look", "speak", "play"] },
  { id: "music-v-006", theme: "music", type: "vocabulary", level: "beginner", english: "drum", spanish: "tambor", phonetic: "dram", exampleEn: "He plays the drum.", exampleEs: "Él toca el tambor.", tags: ["noun", "instrument"], distractorsEs: ["guitarra", "piano", "flauta"], distractorsEn: ["guitar", "piano", "flute"] },
  { id: "music-v-007", theme: "music", type: "vocabulary", level: "beginner", english: "guitar", spanish: "guitarra", phonetic: "guitár", exampleEn: "She plays the guitar.", exampleEs: "Ella toca la guitarra.", tags: ["noun", "instrument"], distractorsEs: ["tambor", "piano", "violín"], distractorsEn: ["drum", "piano", "violin"] },
  { id: "music-v-008", theme: "music", type: "vocabulary", level: "elementary", english: "concert", spanish: "concierto", phonetic: "cónsert", exampleEn: "The concert was amazing!", exampleEs: "¡El concierto fue increíble!", tags: ["noun", "event"], distractorsEs: ["festival", "fiesta", "clase"], distractorsEn: ["festival", "party", "class"] },
  { id: "music-v-009", theme: "music", type: "vocabulary", level: "elementary", english: "singer", spanish: "cantante", phonetic: "sínger", exampleEn: "She is a great singer.", exampleEs: "Ella es una gran cantante.", tags: ["noun", "person"], distractorsEs: ["bailarín", "músico", "DJ"], distractorsEn: ["dancer", "musician", "DJ"] },
  { id: "music-v-010", theme: "music", type: "vocabulary", level: "elementary", english: "piano", spanish: "piano", phonetic: "piáno", exampleEn: "I'm learning to play the piano.", exampleEs: "Estoy aprendiendo a tocar el piano.", tags: ["noun", "instrument"], distractorsEs: ["guitarra", "violín", "batería"], distractorsEn: ["guitar", "violin", "drums"] },
  { id: "music-v-011", theme: "music", type: "vocabulary", level: "elementary", english: "band", spanish: "banda", phonetic: "band", exampleEn: "My favorite band is coming!", exampleEs: "¡Mi banda favorita va a venir!", tags: ["noun", "group"], distractorsEs: ["cantante", "DJ", "orquesta"], distractorsEn: ["singer", "DJ", "orchestra"] },
  { id: "music-v-012", theme: "music", type: "vocabulary", level: "elementary", english: "rhythm", spanish: "ritmo", phonetic: "rídom", exampleEn: "This song has a great rhythm.", exampleEs: "Esta canción tiene un gran ritmo.", tags: ["noun", "quality"], distractorsEs: ["melodía", "letra", "volumen"], distractorsEn: ["melody", "lyrics", "volume"] },
  { id: "music-v-013", theme: "music", type: "vocabulary", level: "intermediate", english: "lyrics", spanish: "letra", phonetic: "lírics", exampleEn: "I know all the lyrics.", exampleEs: "Me sé toda la letra.", tags: ["noun", "text"], distractorsEs: ["ritmo", "melodía", "acorde"], distractorsEn: ["rhythm", "melody", "chord"] },
  { id: "music-v-014", theme: "music", type: "vocabulary", level: "intermediate", english: "rehearsal", spanish: "ensayo", phonetic: "rijérsal", exampleEn: "We have rehearsal at 5.", exampleEs: "Tenemos ensayo a las 5.", tags: ["noun", "practice"], distractorsEs: ["concierto", "clase", "examen"], distractorsEn: ["concert", "class", "exam"] },
  { id: "music-v-015", theme: "music", type: "vocabulary", level: "intermediate", english: "melody", spanish: "melodía", phonetic: "mélodi", exampleEn: "What a beautiful melody!", exampleEs: "¡Qué melodía tan bonita!", tags: ["noun", "quality"], distractorsEs: ["ruido", "silencio", "letra"], distractorsEn: ["noise", "silence", "lyrics"] },
  // Music phrases
  { id: "music-p-001", theme: "music", type: "phrase", level: "beginner", english: "Turn up the music!", spanish: "¡Sube la música!", phonetic: "tern ap de miúsic", exampleEn: "This is my song! Turn up the music!", exampleEs: "¡Esta es mi canción! ¡Sube la música!", tags: ["command", "fun"], distractorsEs: ["¡Baja la música!", "¡Para la música!", "¡Cambia la canción!"], distractorsEn: ["Turn down the music!", "Stop the music!", "Change the song!"] },
  { id: "music-p-002", theme: "music", type: "phrase", level: "elementary", english: "Can you play an instrument?", spanish: "¿Sabes tocar un instrumento?", phonetic: "can yú pléi an ínstrument", exampleEn: "Can you play an instrument? I play guitar.", exampleEs: "¿Sabes tocar un instrumento? Yo toco guitarra.", tags: ["question", "social"], distractorsEs: ["¿Te gusta cantar?", "¿Bailas bien?", "¿Vas a conciertos?"], distractorsEn: ["Do you like singing?", "Do you dance well?", "Do you go to concerts?"] },

  // ============================================================
  // THEME: DAILY LIFE (daily-life)
  // ============================================================
  { id: "daily-v-001", theme: "daily-life", type: "vocabulary", level: "beginner", english: "house", spanish: "casa", phonetic: "jáus", exampleEn: "I live in a big house.", exampleEs: "Vivo en una casa grande.", tags: ["noun", "place"], distractorsEs: ["escuela", "parque", "tienda"], distractorsEn: ["school", "park", "shop"] },
  { id: "daily-v-002", theme: "daily-life", type: "vocabulary", level: "beginner", english: "eat", spanish: "comer", phonetic: "íit", exampleEn: "I eat breakfast at 8.", exampleEs: "Desayuno a las 8.", tags: ["verb", "basic"], distractorsEs: ["dormir", "jugar", "correr"], distractorsEn: ["sleep", "play", "run"] },
  { id: "daily-v-003", theme: "daily-life", type: "vocabulary", level: "beginner", english: "sleep", spanish: "dormir", phonetic: "slíip", exampleEn: "I sleep at 9 o'clock.", exampleEs: "Duermo a las 9.", tags: ["verb", "basic"], distractorsEs: ["comer", "jugar", "estudiar"], distractorsEn: ["eat", "play", "study"] },
  { id: "daily-v-004", theme: "daily-life", type: "vocabulary", level: "beginner", english: "family", spanish: "familia", phonetic: "fámili", exampleEn: "I love my family.", exampleEs: "Quiero a mi familia.", tags: ["noun", "people"], distractorsEs: ["amigos", "vecinos", "compañeros"], distractorsEn: ["friends", "neighbors", "classmates"] },
  { id: "daily-v-005", theme: "daily-life", type: "vocabulary", level: "beginner", english: "morning", spanish: "mañana", phonetic: "mórning", exampleEn: "Good morning!", exampleEs: "¡Buenos días!", tags: ["noun", "time"], distractorsEs: ["tarde", "noche", "mediodía"], distractorsEn: ["afternoon", "night", "noon"] },
  { id: "daily-v-006", theme: "daily-life", type: "vocabulary", level: "beginner", english: "night", spanish: "noche", phonetic: "náit", exampleEn: "Good night! Sleep well.", exampleEs: "¡Buenas noches! Duerme bien.", tags: ["noun", "time"], distractorsEs: ["mañana", "tarde", "día"], distractorsEn: ["morning", "afternoon", "day"] },
  { id: "daily-v-007", theme: "daily-life", type: "vocabulary", level: "beginner", english: "water", spanish: "agua", phonetic: "uóter", exampleEn: "Can I have some water?", exampleEs: "¿Puedo tener un poco de agua?", tags: ["noun", "drink"], distractorsEs: ["leche", "zumo", "refresco"], distractorsEn: ["milk", "juice", "soda"] },
  { id: "daily-v-008", theme: "daily-life", type: "vocabulary", level: "beginner", english: "happy", spanish: "feliz", phonetic: "jápi", exampleEn: "I am happy today.", exampleEs: "Estoy feliz hoy.", tags: ["adjective", "emotion"], distractorsEs: ["triste", "enfadado", "cansado"], distractorsEn: ["sad", "angry", "tired"] },
  { id: "daily-v-009", theme: "daily-life", type: "vocabulary", level: "beginner", english: "friend", spanish: "amigo", phonetic: "frénd", exampleEn: "She is my best friend.", exampleEs: "Ella es mi mejor amiga.", tags: ["noun", "people"], distractorsEs: ["hermano", "primo", "vecino"], distractorsEn: ["brother", "cousin", "neighbor"] },
  { id: "daily-v-010", theme: "daily-life", type: "vocabulary", level: "beginner", english: "help", spanish: "ayudar", phonetic: "jelp", exampleEn: "Can you help me?", exampleEs: "¿Puedes ayudarme?", tags: ["verb", "basic"], distractorsEs: ["hablar", "llamar", "preguntar"], distractorsEn: ["talk", "call", "ask"] },
  { id: "daily-v-011", theme: "daily-life", type: "vocabulary", level: "elementary", english: "shower", spanish: "ducha", phonetic: "sháuer", exampleEn: "I take a shower every morning.", exampleEs: "Me ducho todas las mañanas.", tags: ["noun", "hygiene"], distractorsEs: ["baño", "piscina", "lavabo"], distractorsEn: ["bath", "pool", "sink"] },
  { id: "daily-v-012", theme: "daily-life", type: "vocabulary", level: "elementary", english: "homework", spanish: "deberes", phonetic: "jómuork", exampleEn: "I need to do my homework.", exampleEs: "Necesito hacer mis deberes.", tags: ["noun", "school"], distractorsEs: ["examen", "clase", "recreo"], distractorsEn: ["exam", "class", "break"] },
  { id: "daily-v-013", theme: "daily-life", type: "vocabulary", level: "elementary", english: "brush teeth", spanish: "cepillarse los dientes", phonetic: "brash tíiz", exampleEn: "Brush your teeth before bed.", exampleEs: "Cepíllate los dientes antes de dormir.", tags: ["verb phrase", "hygiene"], distractorsEs: ["lavarse la cara", "peinarse", "vestirse"], distractorsEn: ["wash face", "comb hair", "get dressed"] },
  { id: "daily-v-014", theme: "daily-life", type: "vocabulary", level: "elementary", english: "clean", spanish: "limpiar", phonetic: "clíin", exampleEn: "Help me clean the room.", exampleEs: "Ayúdame a limpiar la habitación.", tags: ["verb", "chore"], distractorsEs: ["ensuciar", "ordenar", "cocinar"], distractorsEn: ["dirty", "tidy", "cook"] },
  { id: "daily-v-015", theme: "daily-life", type: "vocabulary", level: "intermediate", english: "routine", spanish: "rutina", phonetic: "rutíin", exampleEn: "My morning routine is simple.", exampleEs: "Mi rutina de la mañana es sencilla.", tags: ["noun", "habit"], distractorsEs: ["sorpresa", "aventura", "fiesta"], distractorsEn: ["surprise", "adventure", "party"] },
  { id: "daily-v-016", theme: "daily-life", type: "vocabulary", level: "intermediate", english: "neighborhood", spanish: "barrio", phonetic: "néiberjud", exampleEn: "My neighborhood is very quiet.", exampleEs: "Mi barrio es muy tranquilo.", tags: ["noun", "place"], distractorsEs: ["ciudad", "país", "pueblo"], distractorsEn: ["city", "country", "town"] },
  // Daily life phrases
  { id: "daily-p-001", theme: "daily-life", type: "phrase", level: "beginner", english: "Good morning!", spanish: "¡Buenos días!", phonetic: "gud mórning", exampleEn: "Good morning! How are you?", exampleEs: "¡Buenos días! ¿Cómo estás?", tags: ["greeting", "daily"], distractorsEs: ["¡Buenas noches!", "¡Adiós!", "¡Hola!"], distractorsEn: ["Good night!", "Goodbye!", "Hello!"] },
  { id: "daily-p-002", theme: "daily-life", type: "phrase", level: "beginner", english: "How are you?", spanish: "¿Cómo estás?", phonetic: "jáu ar yú", exampleEn: "Hi! How are you today?", exampleEs: "¡Hola! ¿Cómo estás hoy?", tags: ["greeting", "question"], distractorsEs: ["¿Dónde estás?", "¿Qué haces?", "¿Quién eres?"], distractorsEn: ["Where are you?", "What are you doing?", "Who are you?"] },
  { id: "daily-p-003", theme: "daily-life", type: "phrase", level: "beginner", english: "I'm fine, thanks!", spanish: "¡Estoy bien, gracias!", phonetic: "áim fáin, zenks", exampleEn: "I'm fine, thanks! And you?", exampleEs: "¡Estoy bien, gracias! ¿Y tú?", tags: ["response", "daily"], distractorsEs: ["Estoy mal", "No sé", "No quiero"], distractorsEn: ["I'm not well", "I don't know", "I don't want to"] },
  { id: "daily-p-004", theme: "daily-life", type: "phrase", level: "elementary", english: "What time is it?", spanish: "¿Qué hora es?", phonetic: "uót táim is it", exampleEn: "Excuse me, what time is it?", exampleEs: "Disculpa, ¿qué hora es?", tags: ["question", "time"], distractorsEs: ["¿Qué día es?", "¿Dónde estamos?", "¿Cuánto cuesta?"], distractorsEn: ["What day is it?", "Where are we?", "How much is it?"] },
  { id: "daily-p-005", theme: "daily-life", type: "phrase", level: "intermediate", english: "I'm running late", spanish: "Voy tarde", phonetic: "áim ráning léit", exampleEn: "Sorry, I'm running late today.", exampleEs: "Lo siento, voy tarde hoy.", tags: ["expression", "time"], distractorsEs: ["Voy temprano", "Tengo tiempo", "No tengo prisa"], distractorsEn: ["I'm early", "I have time", "I'm not in a hurry"] },

  // ============================================================
  // THEME: SCHOOL (school)
  // ============================================================
  { id: "school-v-001", theme: "school", type: "vocabulary", level: "beginner", english: "book", spanish: "libro", phonetic: "búk", exampleEn: "Open your book, please.", exampleEs: "Abre tu libro, por favor.", tags: ["noun", "supply"], distractorsEs: ["cuaderno", "lápiz", "mochila"], distractorsEn: ["notebook", "pencil", "backpack"] },
  { id: "school-v-002", theme: "school", type: "vocabulary", level: "beginner", english: "teacher", spanish: "profesor", phonetic: "tícher", exampleEn: "The teacher is very nice.", exampleEs: "El profesor es muy amable.", tags: ["noun", "person"], distractorsEs: ["estudiante", "director", "conserje"], distractorsEn: ["student", "principal", "janitor"] },
  { id: "school-v-003", theme: "school", type: "vocabulary", level: "beginner", english: "school", spanish: "escuela", phonetic: "eskúul", exampleEn: "I go to school every day.", exampleEs: "Voy a la escuela todos los días.", tags: ["noun", "place"], distractorsEs: ["casa", "parque", "tienda"], distractorsEn: ["house", "park", "shop"] },
  { id: "school-v-004", theme: "school", type: "vocabulary", level: "beginner", english: "read", spanish: "leer", phonetic: "ríid", exampleEn: "I like to read books.", exampleEs: "Me gusta leer libros.", tags: ["verb", "basic"], distractorsEs: ["escribir", "hablar", "dibujar"], distractorsEn: ["write", "speak", "draw"] },
  { id: "school-v-005", theme: "school", type: "vocabulary", level: "beginner", english: "write", spanish: "escribir", phonetic: "ráit", exampleEn: "Write your name here.", exampleEs: "Escribe tu nombre aquí.", tags: ["verb", "basic"], distractorsEs: ["leer", "dibujar", "borrar"], distractorsEn: ["read", "draw", "erase"] },
  { id: "school-v-006", theme: "school", type: "vocabulary", level: "beginner", english: "pencil", spanish: "lápiz", phonetic: "pénsol", exampleEn: "Do you have a pencil?", exampleEs: "¿Tienes un lápiz?", tags: ["noun", "supply"], distractorsEs: ["bolígrafo", "goma", "regla"], distractorsEn: ["pen", "eraser", "ruler"] },
  { id: "school-v-007", theme: "school", type: "vocabulary", level: "beginner", english: "class", spanish: "clase", phonetic: "clas", exampleEn: "My class starts at 9.", exampleEs: "Mi clase empieza a las 9.", tags: ["noun", "event"], distractorsEs: ["recreo", "examen", "fiesta"], distractorsEn: ["break", "exam", "party"] },
  { id: "school-v-008", theme: "school", type: "vocabulary", level: "beginner", english: "learn", spanish: "aprender", phonetic: "lern", exampleEn: "I want to learn English.", exampleEs: "Quiero aprender inglés.", tags: ["verb", "basic"], distractorsEs: ["enseñar", "olvidar", "recordar"], distractorsEn: ["teach", "forget", "remember"] },
  { id: "school-v-009", theme: "school", type: "vocabulary", level: "elementary", english: "notebook", spanish: "cuaderno", phonetic: "nóutbuk", exampleEn: "Write it in your notebook.", exampleEs: "Escríbelo en tu cuaderno.", tags: ["noun", "supply"], distractorsEs: ["libro", "agenda", "carpeta"], distractorsEn: ["book", "planner", "folder"] },
  { id: "school-v-010", theme: "school", type: "vocabulary", level: "elementary", english: "exam", spanish: "examen", phonetic: "igzám", exampleEn: "The exam is on Friday.", exampleEs: "El examen es el viernes.", tags: ["noun", "assessment"], distractorsEs: ["tarea", "clase", "recreo"], distractorsEn: ["homework", "class", "break"] },
  { id: "school-v-011", theme: "school", type: "vocabulary", level: "elementary", english: "subject", spanish: "asignatura", phonetic: "sábject", exampleEn: "What is your favorite subject?", exampleEs: "¿Cuál es tu asignatura favorita?", tags: ["noun", "academic"], distractorsEs: ["deporte", "juego", "hobby"], distractorsEn: ["sport", "game", "hobby"] },
  { id: "school-v-012", theme: "school", type: "vocabulary", level: "elementary", english: "break", spanish: "recreo", phonetic: "bréik", exampleEn: "It's break time!", exampleEs: "¡Es hora del recreo!", tags: ["noun", "time"], distractorsEs: ["clase", "examen", "tarea"], distractorsEn: ["class", "exam", "homework"] },
  { id: "school-v-013", theme: "school", type: "vocabulary", level: "intermediate", english: "schedule", spanish: "horario", phonetic: "skédiul", exampleEn: "Check the schedule for tomorrow.", exampleEs: "Mira el horario de mañana.", tags: ["noun", "organization"], distractorsEs: ["calendario", "agenda", "reloj"], distractorsEn: ["calendar", "planner", "clock"] },
  { id: "school-v-014", theme: "school", type: "vocabulary", level: "intermediate", english: "presentation", spanish: "presentación", phonetic: "presentéishon", exampleEn: "I have a presentation today.", exampleEs: "Tengo una presentación hoy.", tags: ["noun", "task"], distractorsEs: ["examen", "debate", "proyecto"], distractorsEn: ["exam", "debate", "project"] },
  // School phrases
  { id: "school-p-001", theme: "school", type: "phrase", level: "beginner", english: "Can I go to the bathroom?", spanish: "¿Puedo ir al baño?", phonetic: "can ái góu tu de bázrum", exampleEn: "Excuse me, can I go to the bathroom?", exampleEs: "Disculpe, ¿puedo ir al baño?", tags: ["request", "classroom"], distractorsEs: ["¿Puedo salir?", "¿Puedo comer?", "¿Puedo jugar?"], distractorsEn: ["Can I leave?", "Can I eat?", "Can I play?"] },
  { id: "school-p-002", theme: "school", type: "phrase", level: "beginner", english: "I don't understand", spanish: "No entiendo", phonetic: "ái dóunt anderstánd", exampleEn: "Sorry, I don't understand.", exampleEs: "Lo siento, no entiendo.", tags: ["expression", "help"], distractorsEs: ["Ya entiendo", "Es fácil", "No me importa"], distractorsEn: ["I understand now", "It's easy", "I don't care"] },
  { id: "school-p-003", theme: "school", type: "phrase", level: "elementary", english: "Can you repeat that?", spanish: "¿Puedes repetir eso?", phonetic: "can yú ripíit dat", exampleEn: "Sorry, can you repeat that, please?", exampleEs: "Perdona, ¿puedes repetir eso, por favor?", tags: ["request", "classroom"], distractorsEs: ["¿Puedes ir más rápido?", "¿Has terminado?", "¿Puedo irme?"], distractorsEn: ["Can you go faster?", "Are you done?", "Can I leave?"] },

  // ============================================================
  // THEME: FOOD & DRINKS (food)
  // ============================================================
  { id: "food-v-001", theme: "food", type: "vocabulary", level: "beginner", english: "pizza", spanish: "pizza", phonetic: "pítsa", exampleEn: "I love pizza!", exampleEs: "¡Me encanta la pizza!", tags: ["noun", "food"], distractorsEs: ["hamburguesa", "pasta", "ensalada"], distractorsEn: ["hamburger", "pasta", "salad"] },
  { id: "food-v-002", theme: "food", type: "vocabulary", level: "beginner", english: "water", spanish: "agua", phonetic: "uóter", exampleEn: "Can I have some water?", exampleEs: "¿Puedo tomar un poco de agua?", tags: ["noun", "drink"], distractorsEs: ["zumo", "leche", "refresco"], distractorsEn: ["juice", "milk", "soda"] },
  { id: "food-v-003", theme: "food", type: "vocabulary", level: "beginner", english: "hungry", spanish: "hambriento", phonetic: "jángri", exampleEn: "I'm very hungry!", exampleEs: "¡Tengo mucha hambre!", tags: ["adjective", "feeling"], distractorsEs: ["sediento", "cansado", "lleno"], distractorsEn: ["thirsty", "tired", "full"] },
  { id: "food-v-004", theme: "food", type: "vocabulary", level: "beginner", english: "fruit", spanish: "fruta", phonetic: "frúut", exampleEn: "Eat more fruit!", exampleEs: "¡Come más fruta!", tags: ["noun", "healthy"], distractorsEs: ["verdura", "carne", "dulce"], distractorsEn: ["vegetable", "meat", "candy"] },
  { id: "food-v-005", theme: "food", type: "vocabulary", level: "beginner", english: "milk", spanish: "leche", phonetic: "milk", exampleEn: "I drink milk for breakfast.", exampleEs: "Bebo leche para desayunar.", tags: ["noun", "drink"], distractorsEs: ["agua", "zumo", "té"], distractorsEn: ["water", "juice", "tea"] },
  { id: "food-v-006", theme: "food", type: "vocabulary", level: "beginner", english: "apple", spanish: "manzana", phonetic: "ápol", exampleEn: "This apple is red.", exampleEs: "Esta manzana es roja.", tags: ["noun", "fruit"], distractorsEs: ["naranja", "plátano", "pera"], distractorsEn: ["orange", "banana", "pear"] },
  { id: "food-v-007", theme: "food", type: "vocabulary", level: "beginner", english: "bread", spanish: "pan", phonetic: "bred", exampleEn: "I eat bread every morning.", exampleEs: "Como pan todas las mañanas.", tags: ["noun", "basic"], distractorsEs: ["arroz", "pasta", "galleta"], distractorsEn: ["rice", "pasta", "cookie"] },
  { id: "food-v-008", theme: "food", type: "vocabulary", level: "beginner", english: "chicken", spanish: "pollo", phonetic: "chíken", exampleEn: "I like chicken for lunch.", exampleEs: "Me gusta el pollo para comer.", tags: ["noun", "meat"], distractorsEs: ["pescado", "carne", "cerdo"], distractorsEn: ["fish", "beef", "pork"] },
  { id: "food-v-009", theme: "food", type: "vocabulary", level: "elementary", english: "recipe", spanish: "receta", phonetic: "résipe", exampleEn: "This is a simple recipe.", exampleEs: "Esta es una receta sencilla.", tags: ["noun", "cooking"], distractorsEs: ["menú", "lista", "ingrediente"], distractorsEn: ["menu", "list", "ingredient"] },
  { id: "food-v-010", theme: "food", type: "vocabulary", level: "elementary", english: "delicious", spanish: "delicioso", phonetic: "delíshus", exampleEn: "This food is delicious!", exampleEs: "¡Esta comida está deliciosa!", tags: ["adjective", "taste"], distractorsEs: ["horrible", "salado", "amargo"], distractorsEn: ["horrible", "salty", "bitter"] },
  { id: "food-v-011", theme: "food", type: "vocabulary", level: "elementary", english: "breakfast", spanish: "desayuno", phonetic: "brékfast", exampleEn: "What do you eat for breakfast?", exampleEs: "¿Qué comes para desayunar?", tags: ["noun", "meal"], distractorsEs: ["almuerzo", "cena", "merienda"], distractorsEn: ["lunch", "dinner", "snack"] },
  { id: "food-v-012", theme: "food", type: "vocabulary", level: "elementary", english: "lunch", spanish: "almuerzo", phonetic: "lanch", exampleEn: "Lunch is at 1 o'clock.", exampleEs: "El almuerzo es a la 1.", tags: ["noun", "meal"], distractorsEs: ["desayuno", "cena", "merienda"], distractorsEn: ["breakfast", "dinner", "snack"] },
  { id: "food-v-013", theme: "food", type: "vocabulary", level: "elementary", english: "spicy", spanish: "picante", phonetic: "espáisi", exampleEn: "This sauce is very spicy!", exampleEs: "¡Esta salsa es muy picante!", tags: ["adjective", "taste"], distractorsEs: ["dulce", "salado", "amargo"], distractorsEn: ["sweet", "salty", "bitter"] },
  { id: "food-v-014", theme: "food", type: "vocabulary", level: "intermediate", english: "ingredient", spanish: "ingrediente", phonetic: "ingrídient", exampleEn: "We need three ingredients.", exampleEs: "Necesitamos tres ingredientes.", tags: ["noun", "cooking"], distractorsEs: ["receta", "plato", "menú"], distractorsEn: ["recipe", "dish", "menu"] },
  { id: "food-v-015", theme: "food", type: "vocabulary", level: "intermediate", english: "vegetarian", spanish: "vegetariano", phonetic: "vechetérian", exampleEn: "I'm vegetarian, no meat please.", exampleEs: "Soy vegetariano, sin carne por favor.", tags: ["adjective", "diet"], distractorsEs: ["carnívoro", "vegano", "alérgico"], distractorsEn: ["carnivore", "vegan", "allergic"] },
  // Food phrases
  { id: "food-p-001", theme: "food", type: "phrase", level: "beginner", english: "I'm hungry!", spanish: "¡Tengo hambre!", phonetic: "áim jángri", exampleEn: "Mom, I'm hungry!", exampleEs: "¡Mamá, tengo hambre!", tags: ["expression", "feeling"], distractorsEs: ["Tengo sed", "Estoy lleno", "No tengo hambre"], distractorsEn: ["I'm thirsty", "I'm full", "I'm not hungry"] },
  { id: "food-p-002", theme: "food", type: "phrase", level: "beginner", english: "Can I have some water?", spanish: "¿Puedo tomar agua?", phonetic: "can ái jav sam uóter", exampleEn: "Excuse me, can I have some water?", exampleEs: "Disculpe, ¿puedo tomar agua?", tags: ["request", "polite"], distractorsEs: ["¿Puedo comer?", "¿Puedo irme?", "¿Puedo jugar?"], distractorsEn: ["Can I eat?", "Can I leave?", "Can I play?"] },
  { id: "food-p-003", theme: "food", type: "phrase", level: "elementary", english: "What's for dinner?", spanish: "¿Qué hay de cena?", phonetic: "uóts for díner", exampleEn: "I'm hungry! What's for dinner?", exampleEs: "¡Tengo hambre! ¿Qué hay de cena?", tags: ["question", "meal"], distractorsEs: ["¿Qué hay de postre?", "¿A qué hora cenamos?", "¿Quién cocina?"], distractorsEn: ["What's for dessert?", "What time is dinner?", "Who's cooking?"] },

  // ============================================================
  // THEME: TRAVEL (travel)
  // ============================================================
  { id: "travel-v-001", theme: "travel", type: "vocabulary", level: "beginner", english: "car", spanish: "coche", phonetic: "car", exampleEn: "We go by car.", exampleEs: "Vamos en coche.", tags: ["noun", "transport"], distractorsEs: ["bus", "tren", "avión"], distractorsEn: ["bus", "train", "plane"] },
  { id: "travel-v-002", theme: "travel", type: "vocabulary", level: "beginner", english: "plane", spanish: "avión", phonetic: "pléin", exampleEn: "The plane is very fast.", exampleEs: "El avión es muy rápido.", tags: ["noun", "transport"], distractorsEs: ["barco", "tren", "coche"], distractorsEn: ["ship", "train", "car"] },
  { id: "travel-v-003", theme: "travel", type: "vocabulary", level: "beginner", english: "train", spanish: "tren", phonetic: "tréin", exampleEn: "I take the train to school.", exampleEs: "Tomo el tren para ir a la escuela.", tags: ["noun", "transport"], distractorsEs: ["bus", "metro", "taxi"], distractorsEn: ["bus", "subway", "taxi"] },
  { id: "travel-v-004", theme: "travel", type: "vocabulary", level: "beginner", english: "beach", spanish: "playa", phonetic: "bíich", exampleEn: "I love the beach!", exampleEs: "¡Me encanta la playa!", tags: ["noun", "place"], distractorsEs: ["montaña", "bosque", "ciudad"], distractorsEn: ["mountain", "forest", "city"] },
  { id: "travel-v-005", theme: "travel", type: "vocabulary", level: "beginner", english: "hotel", spanish: "hotel", phonetic: "joutél", exampleEn: "We stay at a hotel.", exampleEs: "Nos quedamos en un hotel.", tags: ["noun", "place"], distractorsEs: ["casa", "camping", "hostal"], distractorsEn: ["house", "camping", "hostel"] },
  { id: "travel-v-006", theme: "travel", type: "vocabulary", level: "beginner", english: "map", spanish: "mapa", phonetic: "map", exampleEn: "Look at the map!", exampleEs: "¡Mira el mapa!", tags: ["noun", "tool"], distractorsEs: ["brújula", "guía", "foto"], distractorsEn: ["compass", "guide", "photo"] },
  { id: "travel-v-007", theme: "travel", type: "vocabulary", level: "beginner", english: "bus", spanish: "autobús", phonetic: "bas", exampleEn: "The bus is coming.", exampleEs: "El autobús está llegando.", tags: ["noun", "transport"], distractorsEs: ["tren", "taxi", "metro"], distractorsEn: ["train", "taxi", "subway"] },
  { id: "travel-v-008", theme: "travel", type: "vocabulary", level: "beginner", english: "trip", spanish: "viaje", phonetic: "trip", exampleEn: "Have a nice trip!", exampleEs: "¡Buen viaje!", tags: ["noun", "basic"], distractorsEs: ["fiesta", "vacaciones", "aventura"], distractorsEn: ["party", "vacation", "adventure"] },
  { id: "travel-v-009", theme: "travel", type: "vocabulary", level: "elementary", english: "airport", spanish: "aeropuerto", phonetic: "éirport", exampleEn: "We arrived at the airport.", exampleEs: "Llegamos al aeropuerto.", tags: ["noun", "place"], distractorsEs: ["estación", "puerto", "terminal"], distractorsEn: ["station", "port", "terminal"] },
  { id: "travel-v-010", theme: "travel", type: "vocabulary", level: "elementary", english: "passport", spanish: "pasaporte", phonetic: "pásport", exampleEn: "Don't forget your passport!", exampleEs: "¡No olvides tu pasaporte!", tags: ["noun", "document"], distractorsEs: ["maleta", "billete", "mapa"], distractorsEn: ["suitcase", "ticket", "map"] },
  { id: "travel-v-011", theme: "travel", type: "vocabulary", level: "elementary", english: "suitcase", spanish: "maleta", phonetic: "súutkeis", exampleEn: "Pack your suitcase!", exampleEs: "¡Haz tu maleta!", tags: ["noun", "luggage"], distractorsEs: ["mochila", "bolsa", "bolso"], distractorsEn: ["backpack", "bag", "purse"] },
  { id: "travel-v-012", theme: "travel", type: "vocabulary", level: "elementary", english: "ticket", spanish: "billete", phonetic: "tíket", exampleEn: "I bought a train ticket.", exampleEs: "Compré un billete de tren.", tags: ["noun", "document"], distractorsEs: ["pasaporte", "reserva", "recibo"], distractorsEn: ["passport", "reservation", "receipt"] },
  { id: "travel-v-013", theme: "travel", type: "vocabulary", level: "intermediate", english: "destination", spanish: "destino", phonetic: "destinéishon", exampleEn: "What is your destination?", exampleEs: "¿Cuál es tu destino?", tags: ["noun", "travel"], distractorsEs: ["origen", "parada", "ruta"], distractorsEn: ["origin", "stop", "route"] },
  { id: "travel-v-014", theme: "travel", type: "vocabulary", level: "intermediate", english: "boarding pass", spanish: "tarjeta de embarque", phonetic: "bórding pas", exampleEn: "Show your boarding pass.", exampleEs: "Muestra tu tarjeta de embarque.", tags: ["noun", "document"], distractorsEs: ["pasaporte", "billete", "visa"], distractorsEn: ["passport", "ticket", "visa"] },
  // Travel phrases
  { id: "travel-p-001", theme: "travel", type: "phrase", level: "beginner", english: "Where is the bus?", spanish: "¿Dónde está el autobús?", phonetic: "uéar is de bas", exampleEn: "Excuse me, where is the bus?", exampleEs: "Disculpe, ¿dónde está el autobús?", tags: ["question", "transport"], distractorsEs: ["¿Cuánto cuesta?", "¿A qué hora sale?", "¿Dónde vamos?"], distractorsEn: ["How much is it?", "What time does it leave?", "Where are we going?"] },
  { id: "travel-p-002", theme: "travel", type: "phrase", level: "beginner", english: "I'm lost", spanish: "Estoy perdido", phonetic: "áim lost", exampleEn: "Help! I'm lost.", exampleEs: "¡Ayuda! Estoy perdido.", tags: ["expression", "help"], distractorsEs: ["Estoy bien", "Sé el camino", "Ya llegué"], distractorsEn: ["I'm fine", "I know the way", "I've arrived"] },
  { id: "travel-p-003", theme: "travel", type: "phrase", level: "elementary", english: "How do I get there?", spanish: "¿Cómo llego allí?", phonetic: "jáu du ái get dér", exampleEn: "Excuse me, how do I get there?", exampleEs: "Disculpe, ¿cómo llego allí?", tags: ["question", "directions"], distractorsEs: ["¿Cuánto falta?", "¿Está lejos?", "¿Es gratis?"], distractorsEn: ["How far is it?", "Is it far?", "Is it free?"] },
  { id: "travel-p-004", theme: "travel", type: "phrase", level: "intermediate", english: "My flight has been delayed", spanish: "Mi vuelo se ha retrasado", phonetic: "mái fláit jas biin diléid", exampleEn: "Bad news — my flight has been delayed.", exampleEs: "Malas noticias — mi vuelo se ha retrasado.", tags: ["information", "airport"], distractorsEs: ["Mi vuelo ha salido", "Mi vuelo está a tiempo", "Mi vuelo ha llegado"], distractorsEn: ["My flight has departed", "My flight is on time", "My flight has arrived"] },
];
